### ISSUE TITLE
VPT for Swin

### ISSUE THREAD

**Issue by ilovecv** [sagizty/VPT#1]
Hi,

Thanks for sharing the visual prompt tuning for ViT. Do you have any plan for Swin?

**Comment by sagizty** [comment]
A thousand thanks to your attention, it's in the TODO list. Currently I'm design a Prompt Token design to better fit the Shifting-window design. As read in the original paper, the prompt tuning for Swin Transformer is less effective than fine-tuning. Besides, the patch-based ViT groups the tokens equally while the Swin Transformer using shifting windows to use them, (that's also the reason why Swin Transformer do not use CLS token) so I think the Prompt Token in VPT may be improved and it's not currently proposed here.

**Comment by ilovecv** [comment]
Thank you very much for your quick reply. Good luck for your exploration!
