### ISSUE TITLE
AttributeError: 'int' object has no attribute 'obtain_prompt'

### ISSUE THREAD

**Issue by Z-Road** [sagizty/VPT#10]
Traceback (most recent call last):
  File "E:/pytorch_gpu/VPT-main/scratch.py", line 34, in <module>
    prompt_state_dict = model.obtain_prompt()
AttributeError: 'int' object has no attribute 'obtain_prompt'

The above issue occurred while running your code. May I ask how to solve it? Thank you very much for your reply.

**Comment by sagizty** [comment]
Thx for the issue, this error is related to different version of timm's Transformer. 
You can replace the structure.py line 124 
x = self.pre_logits(x[:, 0, :]) 
with 
x = self.fc_norm(x[:, 0, :])

the name of this norm layer before CLS head has been changed in time.
