### ISSUE TITLE
Do you miss a norm_pre() layer here?

### ISSUE THREAD

**Issue by Waybaba** [sagizty/VPT#6]
https://github.com/sagizty/VPT/blob/9022b94abdb3d8ec44e6141293bb4313e79188a7/PromptModels/structure.py#L92

**Comment by sagizty** [comment]
In the code, we import and success “from timm.models.vision_transformer import VisionTransformer” which adopts pre-norm strategy, the norm layer are used inside the transformer encoder block.

**Comment by Waybaba** [comment]
Thanks for your clarification!

**Comment by sagizty** [comment]
🫡take care
