### ISSUE TITLE
What is the function "pre_logits"

### ISSUE THREAD

**Issue by RizhaoCai** [sagizty/VPT#7]
At https://github.com/sagizty/VPT/blob/9022b94abdb3d8ec44e6141293bb4313e79188a7/PromptModels/structure.py#L124
There is `x = self.pre_logits(x[:, 0, :])`. However, there is no function called pre_logits.

What is this?

**Comment by sagizty** [comment]
its inherited from ‘VisionTransformer‘ as VPT is a class based on it.

**Comment by tzhu01** [comment]
If you have some problem about no attri "pre_logits", its just the fc&tanh, you can copy the ViT and patch_embedding from "https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/vision_transformer/vit_model.py",
