### ISSUE TITLE
The shape of input and the forzen network.

### ISSUE THREAD

**Issue by Lecooo** [sagizty/VPT#9]
When using the prompts, they were concat-ed with the origin input and the CLS token. Since the forzen network was trained without prompts, in my opinion, when the prompts were concat-ed with input, the shape of input has been changed, won't fit with the network. So why the nework still works?

I will appreciate your reply!!

**Comment by sagizty** [comment]
Good question! However, Transformer is based on MLP, where the parameters in the model is doing last dimention projection. In FC layer design, it will not encounter error in pytorch as long as the feature dimention of D fixed (the number of nurons). For Transformer(ViT) you can remove positional encoding to try to handle multiple length, as long as it can make the CNN encoding happy.

About MLP's  last dimention projection:
for example, if you have a FC (10->24) layer
you can input [N,10] and you will get [N,24]
N can be any number.

with more dim, it's still doing the last dim projection:
you can input [B,A,N,10] and you will get [B,A,N,24]
